<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Store</title>
</head>
<body>
        <form name="findProductByName" ><input placeholder="Название продукта" type="text" name="inputFindProductByName"/><button type="submit" id="ProductNameId">Искать</button><br></form>
        <form name="findProductByType" ><input placeholder="Тип продукта" name="inputFindProductByType" type="text"/><button type="submit" id="ProductTypeId">Искать</button><br></form>
        <form name="findProductByPrice" ><input placeholder="Цену продукта" name="inputFindProductByPrice" type="number"/><button type="submit" id="ProductPriceId">Искать</button><br></form>
        <form name="findProductByQuantity" ><input placeholder="Количество продукта" name="inputFindProductByQuantity" type="number"/><button type="submit" id="ProductQuantityId">Искать</button><br></form>
        <form name="findStoreByName" ><input placeholder="Название магазина" name="inputFindStoreByName" type="text"/><button type="submit" id="StoreNameId">Искать</button><br></form>
        <form name="findStoreByAddress" ><input placeholder="Адрес магазина" name="inputFindStoreByAddress" type="text"/><button type="submit" id="StoreAddressId">Искать</button><br></form>
        <form name="findStoreByDescription" ><input placeholder="Описание магазина" name="inputFindStoreByDescription" type="text"/><button type="submit" id="StoreDescriptionId">Искать</button><br></form>
</body>
</html>

<script src="js/script.js"></script>